#pragma once

#include "game/sound_event.hpp"
#include "video/character_frame.hpp"

#include <cstddef>
#include <cstdint>
#include <span>
#include <vector>

namespace ghostbusters::game {

class TextScript {
public:
    // Copies through the first FF; the caller may immediately reuse the source.
    void start(std::span<const std::uint8_t> bytes, std::uint8_t column = 8,
               std::uint8_t row = 1, std::uint8_t color = 0);

    [[nodiscard]] bool active() const noexcept;

    // Drain sound intents generated by bytes consumed since the previous
    // call. Text tones are emitted only for actual normal-cadence bytes.
    [[nodiscard]] SoundEvents take_sound_events();
    [[nodiscard]] const std::vector<std::uint8_t>& rendered_bytes() const noexcept { return rendered_bytes_; }

    // Nonzero cadence consumes one byte on selected frames; zero batches 40.
    void tick(video::CharacterFrame& frame,
              std::uint8_t frame_counter, std::uint8_t cadence_mask = 3);

    [[nodiscard]] std::uint8_t column() const noexcept;
    [[nodiscard]] std::uint8_t row() const noexcept;

    // Used by later keyboard/name-entry code to position the same writer.
    void set_cursor(std::uint8_t column, std::uint8_t row);

private:
    void advance_byte(video::CharacterFrame& frame,
                      std::uint8_t cadence_mask);
    [[nodiscard]] std::uint8_t next_source_byte();

    std::size_t runtime_index_ = 0;
    std::vector<std::uint8_t> runtime_bytes_;
    std::uint8_t column_ = 8;
    std::uint8_t row_ = 1;
    std::uint8_t color_ = 0;
    bool active_ = false;
    SoundEvents sound_events_;
    std::vector<std::uint8_t> rendered_bytes_;
};

} // namespace ghostbusters::game
