#!/usr/bin/env python3
"""Validate the checked-in speech blob and embed it in a C++ include."""

import argparse
import hashlib
import json
from pathlib import Path
import struct


ROOT = Path(__file__).resolve().parents[1]
HEADER_BYTES = 8
ENTRY_BYTES = 20
COMMAND_COUNT = 5


def fnv1a_events(events):
    value = 0xCBF29CE484222325
    for tick, sample in events:
        for shift in range(0, 32, 8):
            value ^= (tick >> shift) & 0xFF
            value = (value * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
        value ^= sample
        value = (value * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return value


def decode_blob(blob):
    if blob[:HEADER_BYTES] != b"GBSA\x01\x05\x00\x00":
        raise ValueError("speech asset has an invalid header")
    table_end = HEADER_BYTES + ENTRY_BYTES * COMMAND_COUNT
    if len(blob) < table_end:
        raise ValueError("speech asset has a truncated index")

    commands = []
    for command in range(COMMAND_COUNT):
        timer_latch, reserved, total_ticks, count, offset, size = struct.unpack_from(
            "<HHIIII", blob, HEADER_BYTES + command * ENTRY_BYTES
        )
        if reserved or offset < table_end or offset > len(blob) or size > len(blob) - offset:
            raise ValueError(f"speech command {command} has an invalid range")
        cursor = offset
        previous = 0
        events = []
        for _ in range(count):
            delta = 0
            shift = 0
            while True:
                if cursor >= offset + size or shift > 28:
                    raise ValueError(f"speech command {command} has an invalid tick delta")
                byte = blob[cursor]
                cursor += 1
                delta |= (byte & 0x7F) << shift
                if not byte & 0x80:
                    break
                shift += 7
            if cursor >= offset + size:
                raise ValueError(f"speech command {command} is missing a sample")
            tick = previous + delta
            if tick >= total_ticks or (events and tick <= previous):
                raise ValueError(f"speech command {command} has invalid event ticks")
            events.append((tick, blob[cursor]))
            cursor += 1
            previous = tick
        if cursor != offset + size:
            raise ValueError(f"speech command {command} has trailing bytes")
        encoded = blob[offset:offset + size]
        commands.append({
            "command": command,
            "label": f"command-{command}",
            "timer_latch": timer_latch,
            "total_timer_ticks": total_ticks,
            "event_count": count,
            "encoded_bytes": size,
            "offset": offset,
            "event_fnv1a64": f"{fnv1a_events(events):016x}",
            "encoded_sha256": hashlib.sha256(encoded).hexdigest(),
        })
    return commands


def checked_blob(assets):
    blob = (assets / "speech_assets.bin").read_bytes()
    manifest = json.loads((assets / "speech_assets.json").read_text(encoding="utf-8"))
    expected_format = {
        "magic": "GBSA",
        "version": 1,
        "commands": COMMAND_COUNT,
        "event_encoding": "unsigned LEB128 tick delta followed by one D418 byte",
    }
    digest = hashlib.sha256(blob).hexdigest()
    if (manifest.get("format") != expected_format or
            manifest.get("blob_sha256") != digest or
            manifest.get("commands") != decode_blob(blob)):
        raise ValueError("speech asset manifest does not match the binary")
    return blob, digest


def generated_text(blob, digest):
    lines = [
        "// Generated by tools/embed_speech_assets.py; do not edit by hand.",
        f"// Blob SHA-256: {digest}",
        "namespace ghostbusters::audio::detail {",
        f"inline constexpr std::array<std::uint8_t, {len(blob)}> kSpeechAssetBlob{{{{",
    ]
    for start in range(0, len(blob), 16):
        values = ", ".join(f"0x{byte:02x}" for byte in blob[start:start + 16])
        lines.append(f"    {values},")
    lines.extend(["}};", "} // namespace ghostbusters::audio::detail", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--assets", type=Path, default=ROOT / "assets/audio/speech")
    parser.add_argument("--output", type=Path,
                        default=ROOT / "build/generated/speech_assets.inc")
    parser.add_argument("--verify", action="store_true",
                        help="verify that the existing output also matches the assets")
    args = parser.parse_args()

    blob, digest = checked_blob(args.assets)
    content = generated_text(blob, digest)
    if args.verify:
        if args.output.read_text(encoding="utf-8") != content:
            raise ValueError(f"generated speech include does not match: {args.output}")
        print(f"verified embedded speech assets ({len(blob)} bytes, {COMMAND_COUNT} commands)")
        return
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if not args.output.exists() or args.output.read_text(encoding="utf-8") != content:
        args.output.write_text(content, encoding="utf-8")
    print(f"embedded {len(blob)} speech bytes into {args.output}")


if __name__ == "__main__":
    main()
